<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU05yBS6\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU05yBS6/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerU05yBS6.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerU05yBS6\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerU05yBS6\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'U05yBS6',
    'container.build_id' => '2ae0255f',
    'container.build_time' => 1774259470,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU05yBS6');
